from __future__ import annotations

from typing import Any, Protocol


class PanelClient(Protocol):
    async def authenticate(self) -> None: ...
    async def discover(self) -> dict[str, Any]: ...
    async def list_inbounds(self) -> list[dict[str, Any]]: ...
    async def get_inbound(self, inbound_id: int) -> dict[str, Any]: ...
    async def create_inbound(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    async def update_inbound(self, inbound_id: int, payload: dict[str, Any]) -> dict[str, Any]: ...
    async def delete_inbound(self, inbound_id: int) -> None: ...
    async def server_status(self) -> dict[str, Any]: ...
    async def xray_logs(self, count: int = 20) -> str | None: ...
    async def aclose(self) -> None: ...
